# Model arguments
model_name_or_path: ./qwen2-0.5b/qwen2-0.5b-sft
torch_dtype: float16
use_flash_attention_2: false

# Data training arguments
dataset_mixer:
  OPO-alignment/ListUltraFeedback: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 40

# NDCGTrainer arguments
fp16: True
beta: 0.1
tau: 0.1
list_size: 8
loss_type: neural_ndcg
ablation_type: none

do_eval: true
evaluation_strategy: steps
eval_steps: 200
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: qwen2-0.5b-neural_ndcg
learning_rate: 5.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: ./qwen2-0.5b/qwen2-0.5b-neural_ndcg
overwrite_output_dir: True
run_name: qwen2-0.5b-neural_ndcg
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
